license_id: cc-by
methodology: Other
dataset_source: African Center of Meteorological Applications for Development (ACMAD)
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  2dbc5dcc-1507-470b-a414-0687e0980ecb
data_update_frequency: 14
